name: ML Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ml:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Install git (usually already installed, but safe)
    - name: Ensure git exists
      run: git --version

    # 2️⃣ Clone repo manually
    - name: Clone repository
      run: |
        git clone https://github.com/qas-lab/laura-baird-icse2026.git
        ls

    # 3️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # 4️⃣ Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    # 5️⃣ Install dependencies
    - name: Install dependencies
      working-directory: laura-baird-icse2026
      run: |
        uv sync